bot/urls.py
from django.conf.urls import url
from counter.rss import SeumFeed
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from .views import telegram

urlpatterns = [
    url(r'^webhook/$', telegram.webhook, name='telwebhook'),
    url(r'^link/telegram/(?P<verif_key>.+)/$', telegram.link, name='tellink'),
]

counter/urls.py
from django.conf.urls import url
from counter.rss import SeumFeed
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from .views import counter, hashtag, home, reset, user

urlpatterns = [
    url(r'^$', home.index, name='home'),
    url(r'^toggle-notif/$', home.toggleEmailNotifications,
        name='toggle_email_notifications'),
    url(r'^toggle-sort-score/$', home.toggleScoreSorting,
        name='toggle_sort_score'),

    url(r'^reset-counter/$', counter.reset_counter, name='reset-counter'),
    url(r'^counter/(?P<id_counter>\d+)/$', counter.get, name='counter'),

    url(r'^hashtag/(?P<keyword>.+)/$', hashtag.get, name='hashtag'),

    url(r'^like/$', reset.like, name='like'),

    url(r'^create_user/$', user.create, name='create_user'),

    url(r'^rss/$', SeumFeed()),

    url(r'^login/$', auth_views.login,
        {'template_name': 'login.html'},
        name='login'),
    url(r'^logout/$', auth_views.logout_then_login,
        name='logout'),
    url(r'^password/change/$', auth_views.password_change,
        {'template_name': 'passwordChange.html'},
        name='password_change'),
    url(r'^password/change/done∕$', auth_views.password_change_done,
        {'template_name': 'passwordChangeDone.html'},
        name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset,
        {'template_name': 'passwordReset.html',
         'email_template_name': 'resetEmail.txt',
         'subject_template_name': 'subjectEmail.txt',
         'from_email': 'SeumBook <no-reply@merigoux.ovh>'},
        name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        {'template_name': 'passwordResetConfirm.html'},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        {'template_name': 'passwordResetComplete.html'},
        name='password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        {'template_name': 'passwordResetDone.html'},
        name='password_reset_done'),
    url(r'^', RedirectView.as_view(pattern_name='home')),
]

counter/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _, get_language

import arrow
from babel.dates import format_timedelta


class Counter(models.Model):
    name = models.CharField(_('name'), max_length=60)
    email = models.EmailField(_('email'), max_length=264, default='null@localhost')
    trigramme = models.CharField(
        _('trigram'),
        max_length=3,
        validators=[RegexValidator(regex='^\S{3}$', message=_('Trigram must be 3 characters long.'))]
    )
    user = models.ForeignKey(User, blank=True, null=True, verbose_name=_('associated user'))
    email_notifications = models.BooleanField(_('email notifications'), default=False)
    sort_by_score = models.BooleanField(_('sort by SeumScore'), default=True)

    def __str__(self):
        return _('%(trigram)s (%(name)s)') % {'trigram': self.trigramme, 'name': self.name}

    class Meta:
        verbose_name = _('counter')

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Counter, self).save(*args, **kwargs)


class Reset(models.Model):
    timestamp = models.DateTimeField(_('datetime'), auto_now_add=True)
    reason = models.TextField(_('reason'))
    counter = models.ForeignKey('Counter', related_name='resets', verbose_name=_('victim'))
    who = models.ForeignKey('Counter', related_name='who', verbose_name=_('seum giver'), blank=True, null=True, default=None)

    def __str__(self):
        if self.who is None or self.who == self.counter:
            return _('%(counter)s: %(datetime)s (%(reason)s)') % {
                'counter': self.counter,
                'datetime': arrow.Arrow.fromdatetime(self.timestamp).humanize(locale=(get_language() or 'en')), # dirty hack...
                'reason': self.reason
            }
        else:
            return '%(who)s to %(counter)s : %(datetime)s (%(reason)s)' % {
                'who': self.who,
                'counter': self.counter,
                'datetime': arrow.Arrow.fromdatetime(self.timestamp).humanize(locale=(get_language() or 'en')),
                'reason': self.reason
            }

    class Meta:
        verbose_name = _('reset')
        verbose_name_plural = _('resets')


class Like(models.Model):
    liker = models.ForeignKey('Counter', verbose_name=_('liker'), related_name='likes')
    reset = models.ForeignKey('Reset', verbose_name=_('seum'), related_name='likes')
    timestamp = models.DateTimeField(_('datetime'), auto_now_add=True)

    class Meta:
        verbose_name = _('like')
        verbose_name_plural = _('likes')
        unique_together = ('liker', 'reset')

    def __str__(self):
        return _('%(liker)s likes %(reset)s') % {'liker': self.liker, 'reset': self.reset}


class Keyword(models.Model):
    text = models.CharField('texte', max_length=128, unique=True)

    class Meta:
        verbose_name = _('keyword')
        verbose_name_plural = _('keywords')

    def __str__(self):
        return '#%s' % (self.text)


class Hashtag(models.Model):
    keyword = models.ForeignKey('Keyword', verbose_name=_('hashtag'), related_name='hashtags')
    reset = models.ForeignKey('Reset', verbose_name=_('reset'), related_name='hashtags')

    class Meta:
        verbose_name = _('hashtag')
        verbose_name_plural = _('hashtags')

    def __str__(self):
        return _('%(keyword)s for %(who)s') % {'keyword': self.keyword, 'who': self.reset}

counter/views/counter.py
from datetime import datetime, timedelta
from copy import copy

from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.db.models import Count, Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _, get_language

import arrow
from babel.dates import format_timedelta, format_datetime
from graphos.renderers import gchart
from graphos.sources.model import ModelDataSource

from counter.models import *
from counter.utils import parseSeumReason


@login_required
def get(request, id_counter):
    try:
        myCounter = Counter.objects.get(user__id=request.user.id)
    except Counter.DoesNotExist:
        return HttpResponseRedirect(reverse('login'))

    counter = Counter.objects.prefetch_related(
        # we get the related resets annotated with their number of likes
        Prefetch('resets', queryset=Reset.objects.select_related('who', 'counter').annotate(likes_count=Count('likes'))),
        'resets__likes'
    ).get(pk=id_counter)
    resets = list(counter.resets.order_by('-timestamp'))

    # Display
    if len(resets) == 0:
        counter.lastReset = Reset()
        counter.lastReset.delta = timedelta(0)
        counter.lastReset.noSeum = True
        seumFrequency = _('unknown')
    else:
        firstReset = copy(resets[-1])
        counter.lastReset = resets[0]
        counter.lastReset.noSeum = False
        if counter.lastReset.who is None or counter.lastReset.who == counter:
            counter.lastReset.selfSeum = True
        else:
            counter.lastReset.selfSeum = False

        counter.lastReset.formatted_delta = arrow.Arrow.fromdatetime(counter.lastReset.timestamp).humanize(locale=get_language())
        counter.seumCount = len(resets)
        seumFrequency = format_timedelta((datetime.now() - firstReset.timestamp.replace(tzinfo=None)) / counter.seumCount,
            locale=get_language(), threshold=1)

        counter.lastLikes = list(counter.lastReset.likes.all())
        counter.alreadyLiked = myCounter.id in [l.liker.id for l in counter.lastLikes]
        counter.likes_count = len(counter.lastLikes)
        if counter.likes_count > 0:
            counter.likersString = ", ".join(like.liker.trigramme for like in counter.lastLikes)

    for reset in resets:
        if reset.who is None or reset.who.id == reset.counter.id:
            reset.selfSeum = True
        else:
            reset.selfSeum = False
        reset.date = reset.timestamp

    # Timeline graph
    # Data pre-processing
    if not counter.lastReset.noSeum:
        resets_graph = resets
        for reset in resets_graph:
            reset.timestamp = {
                'v': reset.timestamp.timestamp(),
                'f': arrow.Arrow.fromdatetime(reset.timestamp).humanize(locale=get_language())
            }
            if reset.selfSeum:
                reset.Seum = {'v': 0, 'f': reset.reason}
            else:
                reset.Seum = {'v': 0, 'f': _('From %(who)s: %(reason)s') % {'who': reset.who.trigramme, 'reason': reset.reason}}

        # Drawing the graph
        data = ModelDataSource(resets, fields=['timestamp', 'Seum'])
        chart = gchart.LineChart(data, options={
            'lineWidth': 0,
            'pointSize': 10,
            'title': '',
            'vAxis': {'ticks': []},
            'hAxis': {'ticks': [{
                'v': firstReset.timestamp.timestamp(),
                'f': arrow.Arrow.fromdatetime(firstReset.timestamp).humanize(locale=get_language())
            }, {
                'v': datetime.now().timestamp(),
                'f': 'Présent'}
            ]},
            'legend': 'none',
            'height': 90
        })
    else:
        chart = None

    return render(request, 'counterTemplate.html', {
        'counter': counter,
        'chart': chart,
        'resets': resets,
        'seumFrequency': seumFrequency,
        'myCounter': myCounter,
    })


@login_required
def reset_counter(request):
    # Update Form counter
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        data = dict(request.POST)

        who = Counter.objects.get(pk=int(data['who'][0]))
        reason = data['reason'][0]
        if 'counter' in data.keys():
            counter = Counter.objects.get(pk=int(data['counter'][0]))
        else:
            try:
                counter = Counter.objects.get(trigramme=data['trigramme'][0])
            except Counter.DoesNotExist:
                return HttpResponseRedirect(data['redirect'][0])

        # we check that the seumer is the autenticated user
        if who.user is None or who.user != request.user:
            return HttpResponseRedirect(data['redirect'][0])

        reason = data['reason'][0]
        perform_reset(who, counter, reason)

    return HttpResponseRedirect(data['redirect'][0])


def perform_reset(who, counter, reason):
    reset = Reset(counter=counter, who=who, reason=reason)

    reset.save()

    # Now we deal with the hashtags
    keywords = parseSeumReason(reason)
    Hashtag.objects.bulk_create([Hashtag(reset=reset, keyword=keyword) for keyword in keywords])

    # # We send the emails only to those who want
    # emails = [u['email'] for u in Counter.objects.filter(email_notifications=True).values('email')]
    # # Now send emails to everyone
    # if reset.who is None or reset.who == counter:
    #     selfSeum = True
    # else:
    #     selfSeum = False
    # text_of_email = render_to_string(
    #     'seumEmail.txt', {'reason': reason,
    #                       'name': counter.name,
    #                       'who': reset.who,
    #                       'selfSeum': selfSeum,
    #                       })
    # email_to_send = EmailMessage(
    #     '[SeumBook] ' + counter.trigramme + ' a le seum',
    #     text_of_email,
    #     'SeumMan <seum@merigoux.ovh>', emails, [],
    #     reply_to=emails)
    # email_to_send.send(fail_silently=True)

counter/views/hashtag.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.translation import ugettext as _, get_language

import arrow
from babel.dates import format_timedelta, format_datetime

from counter.models import *


@login_required
def get(request, keyword):
    try:
        keyword = Keyword.objects.get(text=keyword)
    except Keyword.DoesNotExist:
        print('erreur !')
        return HttpResponseRedirect(reverse('home'))

    hashtag = '#' + keyword.text
    resets = Reset.objects.prefetch_related('likes', 'who', 'counter').filter(hashtags__keyword=keyword).order_by('-timestamp')
    totalNumber = resets.count()
    cur_lang = get_language()

    for reset in resets:
        if reset.who is None or reset.who == reset.counter:
            reset.selfSeum = True
        else:
            reset.selfSeum = False
        reset.likeCount = reset.likes.count()
    return render(request, 'hashtagTemplate.html', {
        'hashtag': hashtag,
        'totalNumber': totalNumber,
        'resets': resets,
    })

counter/views/reset.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from counter.models import *


@login_required
def like(request):
    if (request.method == 'POST'):
        # create a form instance and populate it with data from the request:
        data = dict(request.POST)
        liker = Counter.objects.get(pk=data['liker'][0])
        reset = Reset.objects.get(pk=data['reset'][0])
        like = Like.objects.create(liker=liker, reset=reset)
    return HttpResponseRedirect(data['redirect'][0])

counter/views/user.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.utils.translation import ugettext as _

from counter.models import Counter


def create(request):
    if (request.method == 'POST'):
        # create a form instance and populate it with data from the request:
        data = dict(request.POST)
        email = data['email'][0]
        username = email.split('@')[0]
        trigramme = data['trigramme'][0]
        nick = data['nick'][0]
        password1 = data['password1'][0]
        password2 = data['password2'][0]
        email_notifications = 'email_notifications' in data.keys()

        if len(trigramme) != 3:
            error = _("Trigram must be 3 characters long.")
            return render(request, 'createUser.html', {'error': error})

        if password1 != password2:
            error = _("Passwords do not match.")
            return render(request, 'createUser.html', {'error': error})

        try:
            test_user = User.objects.get(email=email)
            error = _("A user with this email address already exists.")
            return render(request, 'createUser.html', {'error': error})
        except User.DoesNotExist:
            try:
                user = User.objects.create_user(username, email, password1)
            except IntegrityError:
                error = _("Use another email address, another user has already this login.")
                return render(request, 'createUser.html', {'error': error})

            counter = Counter.objects.create(name=nick, email=email, trigramme=trigramme, user=user, email_notifications=email_notifications)
            return render(request, 'createUserDone.html', {'login': username})
    else:
        return render(request, 'createUser.html', {'error': None})

counter/templates/baseTemplate.html
{% load i18n %} {% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8" />
	<meta name="author" content="Seum Man" />
	<meta name="keywords" content="seum compteur" />
	<meta name="description" content="Ça fout le seum" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/png" href="{{STATIC_URL}}/favicon.ico" />
	<title>SeumBook™ – {% block title %}{% endblock %}</title>

	{# Load the tag library #} {% load bootstrap3 %} {# Load CSS and JavaScript #} {% bootstrap_css %} {% bootstrap_javascript jquery=True %} {# Display django.contrib.messages as Bootstrap alerts #} {% bootstrap_messages %}

	<style>
		body {
			background-color: #EEEEEE
		}

		.seum-counter {
			height: 100px;
			overflow: auto;
			display: flex;
			align-items: center;
		}

		.primary-counter {
			height: 215px;
			overflow: auto;
			display: flex;
			align-items: center;
		}

		.timeline {
			height: 125px;
		}

		.graphs {
			overflow-y: hidden;
		}

		.graphs>div {
			display: block;
			margin: 0 auto;
		}

		.counter-link,
		.counter-link:hover {
			color: inherit;
			/* blue colors for links too */
			text-decoration: inherit;
			/* no underline */
		}
	</style>

	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<script type="text/javascript">
		google.load("visualization", "1", {
			packages: ["corechart"]
		});

		function revealSeumForm(counterID) {
			document.getElementById('counter' + counterID).style.display = 'inline';
			document.getElementById('button' + counterID).style.display = 'none';
			document.getElementById('reason' + counterID).focus();
		}
	</script>
</head>
<section id="content">
	{% block content %}{% endblock %}
</section>
<div class="container">
	<div class="row text-center" style="padding-top:15px;">
		<form action="{% url 'set_language' %}" method="post">{% csrf_token %} {% if LANGUAGE_CODE == 'fr' %}
			<input name="language" type="hidden" value="en" />
			<input type="submit" class="btn btn-primary" value="English version" /> {% else %}
			<input name="language" type="hidden" value="fr" />
			<input type="submit" class="btn btn-primary" value="Version française" /> {% endif %}
		</form>
	</div>
</div>
</body>

</html>

counter/templates/counterTemplate.html
{% extends 'baseTemplate.html' %}

{% block title %}{{counter.trigramme}}{% endblock %}

{% block content %}
{% load i18n %}
{% load hashtags %}

<div class="text-center">
  <h1>
      <a class="counter-link" href="{% url 'home' %}"><b>{{ counter.trigramme }}</b> <small>{{ counter.name }}</small></a>
  </h1>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-primary">
        <div class="panel-heading">
            <form action="{% url 'like' %}" method="POST" name="like{{counter.id}}">
                {% csrf_token %}
                <input type="hidden" name="liker" value="{{myCounter.id}}" />
                <input type="hidden" name="reset" value="{{counter.lastReset.id}}" <h2 class="panel-title" />
                <input type="hidden" name="redirect" value="{% url 'counter' id_counter=counter.id %}" />
                <a class="counter-link" href="{% url 'counter' id_counter=counter.id %}">
                    <b>{{ counter.trigramme }}</b> <small>{{ counter.name }}</small>
                </a>
                {% if not counter.lastReset.noSeum %}
                {% if counter.alreadyLiked %}
                <span class="pull-right badge" {% if counter.likes_count > 0 %} data-toggle="tooltip" data-placement="top" title="{{ counter.likersString }}" {% endif %}>
                    <span class="glyphicon glyphicon-ok"></span>&emsp;{{ counter.likes_count }}
                </span>
                {% elif counter.id == myCounter.id or counter.lastReset.who.id == myCounter.id %}
                <span class="pull-right badge" {% if counter.likes_count > 0 %} data-toggle="tooltip" data-placement="top" title="{{ counter.likersString }}" {% endif %}>
                    <span class="glyphicon glyphicon-heart"></span>&emsp;{{ counter.likes_count }}
                </span>
                {% else %}
                <a class="pull-right badge" onclick="document.forms['like{{counter.id}}'].submit();">
                    <span class="glyphicon glyphicon-heart"></span>&emsp;{{ counter.likes_count }}
                </a>
                {% endif %}
                {% endif %}
                </h2>
            </form>
        </div>
        <div class="seum-counter panel-body" style="height:125px" id="container{{counter.id}}">
         <div style="width:100%">
          {% if counter.lastReset.noSeum %}
            <strong>{% trans "No seum yet" %}.</strong><br />
          {% else %}
            <strong>
            {% if counter.lastReset.selfSeum %}
              {% trans "Got the seum" %} {{ counter.lastReset.formatted_delta }}.
            {% else %}{% blocktrans with trigram=counter.lastReset.who.trigramme time_ago=counter.lastReset.formatted_delta %}Seum thrown by {{ trigram }} {{ time_ago }}.{% endblocktrans %}
            {% endif %}
            </strong><br />
          {% endif %}

          <p>{{ counter.lastReset.reason | hashtag }}</p>
          <div class="text-center">
            <button id="button{{counter.id}}" class="btn btn-default btn-danger" type="button" onclick="revealSeumForm({{counter.id}})">
              {% trans "Reset the counter" %}
            </button>
          </div>
          <form style="display:none" id="counter{{counter.id}}" action="{% url 'reset-counter' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="reason">{% trans "Motive for the seum:" %}</label>
              <input id="reason{{counter.id}}" type="text" class="form-control" name="reason"></input>
            </div>
            <input type="hidden" name="counter" value="{{counter.id}}"></input>
            <input type="hidden" name="redirect" value="{% url 'counter' id_counter=counter.id %}"></input>
            <input type="hidden" name="who" value="{{myCounter.id}}"></input>
            <div class="text-center">
              <button type="submit" class="btn btn-default btn-success">{% trans "Throw the seum" %}</button>
            </div>
          </form>
         </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Timeline of the seum" %}</h2>
        </div>
        <div class="graphs timeline panel-body">
            {% if counter.lastReset.noSeum %}
              <div class="text-center text-muted">
                <p>{% trans "No timeline of the seum yet..." %}</p>
              </div>
            {% else %}
              {{ chart.as_html }}
            {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">
            {% trans "Seum history" %}
            <small class="badge pull-right">{{ seumFrequency }}/seum</small>
          </h2>
        </div>
        <div class="panel-body">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>{% trans "Date" %}</th>
                <th>{% trans "Motive" %}</th>
                <th>{% trans "Seum thrower" %}</th>
                <th>{% trans "Number of likes" %}</th>
              </tr>
            </thead>
            <tbody>
              {% for reset in resets %}
                <tr>
                  <td><b>{{ reset.date | date:"SHORT_DATETIME_FORMAT" }}</b></td>
                  <td>{{ reset.reason | hashtag }}</td>
                  <td>
                    {% if not reset.selfSeum %}
                      {{ reset.who.trigramme }}
                    {% endif %}
                  </td>
                  <td>{{ reset.likes_count }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="text-center">
    <a class="btn btn-success" href="{% url 'home' %}">{% trans "Back to counters list" %}</a>
  </div>
</div>
</div>

{% endblock %}

counter/templates/createUser.html
{% extends 'baseTemplate.html' %}

{% block title %}Changement du mot de passe{% endblock %}

{% block content %}
{% load i18n %}

<div class="container">
    <div class="row">
        <div class="text-center">
            <h1><a class="counter-link" href="{% url 'home' %}">SeumBook™</a></h1>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h2 class="panel-title">{% trans "Create your seum counter!" %}</h2>
            </div>
            <div class=" panel-body">
                <form method="POST">
                    {% csrf_token %}
                    <p>{% trans "The email address will be used for password reinitialisation. Your login on this website will be the first part of this address (before the @)." %}</p>
                    <div class="form-group">
                        <label for="id_email">{% trans "Email address" %}</label>
                        <input id="id_email" type="email" class="form-control" name="email" required />
                    </div>
                    <p>{% trans "If you check the box below, you will receive an email from <tt>seum@merigoux.ovh</tt> each time someone get the seum on the site. Spamming but so enjoyable, can be deactivated and reactivated later." %}
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" name="email_notifications">
                        <label class="form-check-label">
                            {% trans "Email notifications" %}
                        </label>
                    </div>
                    <p>
                        {% trans "Other users will see your nickname and your trigram only, it will be your seum identity!" %}
                        {% trans "This trigram must be 3 characters long exactly." %}
                    </p>
                    <div class="form-group">
                        <label for="id_trigramme">{% trans "Trigram" %}</label>
                        <input id="id_trigramme" minlength="3" maxlength="3" type="text" class="form-control text-uppercase" name="trigramme" onkeyup="this.value=this.value.toUpperCase();" required />
                    </div>
                    <div class="form-group">
                        <label for="id_nick">{% trans "Nick" %}</label>
                        <input id="id_nick" type="text" class="form-control" name="nick" required />
                    </div>
                    <p>{% trans "I could have required 10 characters with one digit, an emoji, three uppercase letters and two lowercase ones to throw you the seum, but actually you can choose whatever you want." %}</p>
                    <div class="form-group">
                        <label for="id_password1">{% trans "Password" %}</label>
                        <input id="id_password1" type="password" class="form-control" name="password1" required />
                    </div>
                    <div class="form-group">
                        <label for="id_password2">{% trans "Confirm password" %}</label>
                        <input id="id_password2" type="password" class="form-control" name="password2" required />
                    </div>
                    <p>{% trans "If this form has given you the seum, do not forget to reset your counter once you are logged in!" %}</p>
                    <div class="text-center">
                        <button type="submit" class="btn btn-default btn-success">{% trans "Create the counter" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if error %}
    <div class="row">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">{% trans "Error" %}</h2>
            </div>
            <div class=" panel-body">
                <p>{{error}}</p>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

counter/templates/createUserDone.html
{% extends 'baseTemplate.html' %}

{% load i18n %}

{% block title %}{% trans "Password successfully changed!" %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="text-center">
            <h1><a class="counter-link" href="{% url 'home' %}">SeumBook™</a></h1>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h2 class="panel-title">{% trans "Victory!" %}</h2>
            </div>
            <div class=" panel-body">
                <p>{% trans "You have created your counter! Your login is " %} <b>{{ login }}</p>.</p>
                <div class="text-center">
                    <a href="{% url 'login' %}" type="submit" class="btn btn-default btn-success">{% trans "Login to access the website!" %}</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

counter/templates/passwordReset.html
{% extends 'baseTemplate.html' %}

{% load i18n %}

{% block title %}{% trans "Password forgotten" %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="text-center">
            <h1><a class="counter-link" href="{% url 'home' %}">SeumBook™</a></h1>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h2 class="panel-title">{% trans "Reset password" %}</h2>
            </div>
            <div class=" panel-body">
                <form class='' method="POST" action="{% url 'password_reset' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_email">{% trans "Email for the reinitialisation link" %}</label>
                        <input id="id_email" type="email" class="form-control" name="email" required/>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-default btn-success">{% trans "Send" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if form.errors %}
    <div class="row">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">{% trans "Error" %}</h2>
            </div>
            <div class=" panel-body">
                <p>{% trans "You cannot even login... seum!" %}</p>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

counter/templates/passwordResetDone.html
{% extends 'baseTemplate.html' %}

{% load i18n %}

{% block title %}{% trans "Email sent!" %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="text-center">
            <h1><a class="counter-link" href="{% url 'home' %}">SeumBook™</a></h1>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h2 class="panel-title">{% trans "Victory!" %}</h2>
            </div>
            <div class=" panel-body">
                <p>{% trans "We have sent you an email. Follow the instructions to reinitialise your password." %}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}